### PR TITLE
Fix #26: Replace Joda w/ java.time

### LINKED ISSUE #26: Replace Joda Time with JDK's java.time
As the [Joda-Time page states:](https://www.joda.org/joda-time/)

> Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.

I can (hopefully) contribute a PR, if interested.

### PR DESCRIPTION
**Pull request by holyjak**

### CODE REVIEW

**Comment by holyjak** [comment]
I just realized the README would need updating too..

**Comment by holyjak** [comment]
1) I prefer ZDT - as a European I want to create a schedule with my local, Oslo time while the server runs in UTC. ZDT allows me to do that. Or do you disagree?

2) Please do, migrating utils are always welcomed by users! :)

I am looking forward to a release when we get all done...

**Comment by jarohen** [comment]
1. Yep, absolutely agree, I'd like users to be able to submit ZDTs, Instants, Longs, whatever - was a suggestion that the coerce target is Instant given that's closer to what we use internally
3. Yep, let's do that :)

**Comment by holyjak** [comment]
Ok, then it makes sense. Let me have a look...

**Comment by holyjak** [comment]
Changed to Instant

**Comment by holyjak** [comment]
BTW what about releasing a version with this and release a new version with the added migration ns later?

**Comment by jarohen** [comment]
cheers, all merged :smile: I'll deploy a SNAPSHOT release of this, at least, but I'd like to make a couple of other modernisation changes to Chime before I cut 0.3.0

thanks again for the issue and PR, much appreciated!

**Comment by jarohen** [comment]
snapshot release is `[jarohen/chime "0.3.0-20200122.132435-1"]` if you want to depend on a fixed version

**Comment by holyjak** [comment]
Hi! Any ETA for a non-snapshot 0.3.0? Thank you!

PS: Also, related to https://insideclojure.org/2020/02/18/lib-version/, it might be good to rename it to 1.0.0? I bet it is more than stable by now :)

**Comment by jarohen** [comment]
Hey @holyjak - sorry for the delay here - I'd intended to include some other changes in 0.3.0 but unfortunately haven't had a lot of time recently. 

Anyway, they can wait - have deployed 0.3.0 now. I agree with the principle of going to 1.0.0 but that's a decision for when I'm back in the country :) 

Thanks for your help on this release :smile:

**Comment by holyjak** [comment]
My pleasure. Thank you!

**Pull request merged**
